server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - StripPrefix=1
        - id: hotel
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
          filters:
            - StripPrefix=1