spring:
  datasource:
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    hostname: ${auth-service}
    non-secure-port: 8080
    prefer-ip-address: false
    secure-port-enabled: false

logging:
  level:
    org.springframework.web: DEBUG
