server:
  port: 8081

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb?useSSL=false&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/