server:
  port: 8084

spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:mysql://localhost:3306/loyaltydb?useSSL=false&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/