server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?useSSL=false&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/