server:
  port: 8087

spring:
  application:
    name: pricing-service
  datasource:
    url: jdbc:mysql://localhost:3306/pricingdb?useSSL=false&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/